import { Layout } from '@/components/layout'
import '../styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Layout>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Layout>
  )
}
